package com.tweetApp.document;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.persistence.*;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Data
@DynamoDBTable(tableName = "Tweets")
public class Tweets {

    @DynamoDBHashKey(attributeName = "tweetId")
    @DynamoDBAutoGeneratedKey
    private String tweetId;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private String tag;

    @DynamoDBAttribute
    private String createdById;

    @DynamoDBAttribute
    private String createdByName;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updateDateTime;

    @Min(value = 0)
    @DynamoDBAttribute
    private long tweetLikesCount;

    @DynamoDBAttribute
    private List<TweetReply> tweetReply=new ArrayList<>();

    @DynamoDBAttribute
    private List<TweetLikes> tweetLikes=new ArrayList<>();


    static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {
        @Override
        public String convert( final LocalDateTime time ) {
            return time.toString();
        }
        @Override
        public LocalDateTime unconvert( final String stringValue ) {
            return LocalDateTime.parse(stringValue);
        }
    }
}
